version: '3'
services:
  rsync:
    build:
      context: https://github.com/qdm12/rsync-docker.git
      dockerfile: Dockerfile.local
    image: qmcgaw/rsync
    container_name: rsync
    command: --archive --compress --progress --delete /source/ /destination/
    volumes:
      - ./source:/source:ro
      - ./destination:/destination
    network_mode: bridge
    restart: always
