version: '3'
services:
  rsync:
    build:
      context: https://github.com/qdm12/rsync-docker.git
      dockerfile: Dockerfile.ssh-client
    image: qmcgaw/rsync:ssh-client
    container_name: rsync-ssh-client
    command: sshUser@sshHost:/source/ /destination/
    volumes:
      - ./key:/home/user/id_rsa:ro
      - ./destination:/destination
    network_mode: bridge
    restart: always
