version: '3'
services:
  rsync:
    build:
      context: https://github.com/qdm12/rsync-docker.git
      dockerfile: Dockerfile.ssh-client
    image: qmcgaw/rsync:ssh-client
    container_name: rsync-ssh-client
    command: /source/ sshUser@sshHost:/destination/
    volumes:
      - ./key:/home/user/id_rsa:ro
      - ./source:/source:ro
    network_mode: bridge
    restart: always
